######################################################
# Source Particle
######################################################
/gps/particle gamma
/gps/ene/mono 511. keV

######################################################
# Source Geometry
######################################################
/gps/pos/type Plane
/gps/pos/shape Square
/gps/pos/centre 0. 0. 20 mm
/gps/pos/halfx 2.5 mm
/gps/pos/halfy 2.5 mm
/gps/direction 0. 0. -1.

######################################################
# RANDOM NUMBER
######################################################
/random/setSeeds 165127 668831

######################################################
# Start Run
######################################################
/analysis/setFileName ../data/test.root
/run/printProgress 10
/run/beamOn 10
